Log:
    Level: "debug"
Http:
    ListenAddress: "0.0.0.0"
    ListenPort: 8088
    CertFile: "rootfs/etc/server.crt"
    KeyFile: "rootfs/etc/server.key"
    StaticRoot: "../frontend/dist/"
    Auth:
        Enabled: true

Database:
    Rdb:
        Debug: true
        DSN: "nas.db?mode=rwc"
        AutoMigrateLevel: "auto"
        MaxConnCount: 10
#  Mongo:
#    Debug: true
#    Address: "192.168.0.231"
#    Port: 27017
#    Username: "root"
#    Password: "123456"
#    Database: "admin"
#    AutoMigrateLevel: "auto"
#    MaxConnCount: 10
Nas:
    SimpleUploadRoot: "/data"
    RealFilenamePolicy: "origin"

MDNS:
    Enabled: true
    ServiceName: "_http._tcp"
    Hostname: "nas.local"
    Info: "NAS Web Service"
